import sqlite3
import json
from datetime import datetime
import logging
from typing import Dict, Any, List, Optional

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class QuoteDatabase:
    """SQLite storage for freight quotes generated by our agent."""

    def __init__(self, db_file: str = "quotes.db") -> None:
        self.db_file = db_file
        self._init_database()

    # ---------- setup ----------

    def _init_database(self) -> None:
        """Create tables and indexes if they do not exist."""
        try:
            conn = sqlite3.connect(self.db_file)
            cursor = conn.cursor()

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS quotes (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    quote_id TEXT UNIQUE,
                    customer_email TEXT NOT NULL,
                    customer_name TEXT,
                    subject TEXT,
                    origin_city TEXT,
                    origin_state TEXT,
                    origin_zip TEXT,
                    destination_city TEXT,
                    destination_state TEXT,
                    destination_zip TEXT,
                    weight_lbs REAL,
                    pieces INTEGER,
                    commodity TEXT,
                    special_services TEXT,
                    total_cost REAL,
                    transit_days INTEGER,
                    quote_data TEXT,
                    pdf_path TEXT,
                    email_body TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    status TEXT DEFAULT 'sent'
                )
                """
            )

            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_quote_id ON quotes(quote_id)"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_customer_email ON quotes(customer_email)"
            )
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_created_at ON quotes(created_at)"
            )

            conn.commit()
            conn.close()
            logger.info("Quote database initialized.")
        except Exception as e:
            logger.error(f"Error initializing database: {e}")

    # ---------- core operations ----------

    def save_quote(
        self,
        quote_data: Dict[str, Any],
        shipment_data: Dict[str, Any],
        email_data: Dict[str, Any],
        pdf_path: str,
    ) -> bool:
        """
        Store a single quote row.

        quote_data: output from PricingEngine / your quoting logic
        shipment_data: dict from ShipmentParser (origin/destination/cargo/...)
        email_data: dict from gmail_integration (id, from, subject, body, date)
        pdf_path: path to generated PDF file
        """
        try:
            conn = sqlite3.connect(self.db_file)
            cursor = conn.cursor()

            # Parse customer email and name from "From" header
            from_header = email_data.get("from", "")
            if "<" in from_header and ">" in from_header:
                customer_email = from_header.split("<")[-1].split(">")[0].strip()
                customer_name = from_header.split("<")[0].strip().strip('"')
            else:
                customer_email = from_header
                customer_name = None

            origin = shipment_data.get("origin", {}) or {}
            dest = shipment_data.get("destination", {}) or {}
            cargo = shipment_data.get("cargo", {}) or {}

            special_services_json = json.dumps(
                shipment_data.get("special_services", [])
            )

            full_quote_json = json.dumps(
                {
                    "quote": quote_data,
                    "shipment": shipment_data,
                    "email_metadata": {
                        "id": email_data.get("id", ""),
                        "subject": email_data.get("subject", ""),
                        "from": email_data.get("from", ""),
                        "date": email_data.get("date", ""),
                    },
                }
            )

            cursor.execute(
                """
                INSERT INTO quotes (
                    quote_id, customer_email, customer_name, subject,
                    origin_city, origin_state, origin_zip,
                    destination_city, destination_state, destination_zip,
                    weight_lbs, pieces, commodity, special_services,
                    total_cost, transit_days, quote_data, pdf_path, email_body
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    quote_data.get("quote_id", ""),
                    customer_email,
                    customer_name,
                    email_data.get("subject", ""),
                    origin.get("city", ""),
                    origin.get("state", ""),
                    origin.get("zip", ""),
                    dest.get("city", ""),
                    dest.get("state", ""),
                    dest.get("zip", ""),
                    cargo.get("weight_lbs", 0),
                    cargo.get("pieces", 0),
                    cargo.get("commodity", ""),
                    special_services_json,
                    quote_data.get("total_cost", 0),
                    quote_data.get("transit_days", 0),
                    full_quote_json,
                    pdf_path,
                    email_data.get("body", ""),
                ),
            )

            conn.commit()
            conn.close()
            logger.info("Quote %s saved.", quote_data.get("quote_id", ""))
            return True
        except Exception as e:
            logger.error(f"Error saving quote: {e}")
            return False

    def get_quote(self, quote_id: str) -> Optional[Dict[str, Any]]:
        """Fetch a single quote by its business quote_id."""
        try:
            conn = sqlite3.connect(self.db_file)
            cursor = conn.cursor()

            cursor.execute(
                "SELECT * FROM quotes WHERE quote_id = ?", (quote_id,)
            )
            row = cursor.fetchone()

            if not row:
                conn.close()
                return None

            columns = [desc[0] for desc in cursor.description]
            quote = dict(zip(columns, row))

            if quote.get("special_services"):
                quote["special_services"] = json.loads(quote["special_services"])
            if quote.get("quote_data"):
                quote["quote_data"] = json.loads(quote["quote_data"])

            conn.close()
            return quote
        except Exception as e:
            logger.error(f"Error retrieving quote {quote_id}: {e}")
            return None

    def get_quotes_by_email(self, customer_email: str):
        """All quotes for a given customer email."""
        try:
            conn = sqlite3.connect(self.db_file)
            cursor = conn.cursor()
            cursor.execute(
                """
                SELECT quote_id, customer_name, subject, total_cost, created_at, status
                FROM quotes
                WHERE customer_email = ?
                ORDER BY created_at DESC
                """,
                (customer_email,),
            )
            rows = cursor.fetchall()
            conn.close()
            return rows
        except Exception as e:
            logger.error(f"Error retrieving quotes for {customer_email}: {e}")
            return []

    def get_recent_quotes(self, limit: int = 10):
        """Recent quotes for dashboard / CLI."""
        try:
            conn = sqlite3.connect(self.db_file)
            cursor = conn.cursor()
            cursor.execute(
                """
                SELECT quote_id, customer_email, customer_name, subject,
                       total_cost, created_at, status
                FROM quotes
                ORDER BY created_at DESC
                LIMIT ?
                """,
                (limit,),
            )
            rows = cursor.fetchall()
            conn.close()
            return rows
        except Exception as e:
            logger.error(f"Error retrieving recent quotes: {e}")
            return []

    def update_quote_status(self, quote_id: str, status: str) -> bool:
        """Update status: sent, viewed, converted, expired, etc."""
        try:
            conn = sqlite3.connect(self.db_file)
            cursor = conn.cursor()
            cursor.execute(
                "UPDATE quotes SET status = ? WHERE quote_id = ?",
                (status, quote_id),
            )
            conn.commit()
            conn.close()
            logger.info("Updated quote %s status to %s", quote_id, status)
            return True
        except Exception as e:
            logger.error(f"Error updating quote status: {e}")
            return False

    # ---------- statistics / debug ----------

    def get_statistics(self) -> Dict[str, Any]:
        """High‑level stats for debugging or a future dashboard."""
        stats: Dict[str, Any] = {}
        try:
            conn = sqlite3.connect(self.db_file)
            cursor = conn.cursor()

            cursor.execute("SELECT COUNT(*) FROM quotes")
            stats["total_quotes"] = cursor.fetchone()[0]

            cursor.execute(
                "SELECT status, COUNT(*) FROM quotes GROUP BY status"
            )
            stats["quotes_by_status"] = dict(cursor.fetchall())

            cursor.execute(
                """
                SELECT DATE(created_at), COUNT(*)
                FROM quotes
                WHERE created_at >= date('now', '-7 days')
                GROUP BY DATE(created_at)
                """
            )
            stats["recent_activity"] = dict(cursor.fetchall())

            cursor.execute(
                """
                SELECT customer_email, COUNT(*) AS quote_count
                FROM quotes
                GROUP BY customer_email
                ORDER BY quote_count DESC
                LIMIT 5
                """
            )
            stats["top_customers"] = cursor.fetchall()

            conn.close()
            return stats
        except Exception as e:
            logger.error(f"Error getting statistics: {e}")
            return stats

    def display_statistics(self) -> None:
        """Pretty-print stats in the console."""
        stats = self.get_statistics()
        print("\n" + "=" * 50)
        print("QUOTE DATABASE STATISTICS")
        print("=" * 50)
        print(f"Total Quotes: {stats.get('total_quotes', 0)}")
        print("Quotes by Status:")
        print(json.dumps(stats.get("quotes_by_status", {}), indent=2))
        print("Recent Activity (last 7 days):")
        print(stats.get("recent_activity", {}))
        print("Top Customers:")
        for email, count in stats.get("top_customers", []):
            print(f"  - {email}: {count} quotes")


# Optional: quick test when run directly
if __name__ == "__main__":
    db = QuoteDatabase()
    db.display_statistics()

    sample_quote = {"quote_id": "TEST-12345", "total_cost": 1250.0, "transit_days": 3}
    sample_shipment = {
        "origin": {"city": "Test City", "state": "TS", "zip": "12345"},
        "destination": {"city": "Test Dest", "state": "TD", "zip": "67890"},
        "cargo": {"weight_lbs": 500, "pieces": 2, "commodity": "test"},
        "special_services": ["liftgate"],
    }
    sample_email = {
        "from": 'Test User <test@example.com>',
        "subject": "Test Quote",
        "body": "Test email body",
        "date": "2024-01-01",
        "id": "EMAIL-ID-TEST",
    }

    ok = db.save_quote(sample_quote, sample_shipment, sample_email, "test.pdf")
    print("Save sample quote:", "OK" if ok else "FAILED")
